notifications:
  email:
    - ilya.rucavitcyn@gmail.com
language: node_js
node_js:
- node
sudo: enabled
branches:
  only:
  - master
before_install:
  - openssl aes-256-cbc -K $encrypted_53d5a51e1c3f_key -iv $encrypted_53d5a51e1c3f_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
before_deploy:
  - ssh-keyscan -H $DEPLOYMENT_HOST >> ~/.ssh/known_hosts
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet --exclude node_modules --exclude deploy_rsa.enc $TRAVIS_BUILD_DIR root@${DEPLOYMENT_HOST}:/opt
